/* Placeholder Series 1: 250 placeholder cards. Generated by tools/make-placeholder-set.js. */
CardSets.register({
  "id": "placeholder",
  "name": "Placeholder Series 1",
  "code": "PH1",
  "description": "Numbered stand-in cards until the real sets are ready.",
  "theme": {
    "primary": "#6d5dfc",
    "secondary": "#12c2e9"
  },
  "pack": {
    "name": "Booster Pack",
    "slots": [
      {
        "count": 5,
        "label": "Common",
        "odds": {
          "common": 100
        }
      },
      {
        "count": 2,
        "label": "Uncommon",
        "odds": {
          "uncommon": 100
        }
      },
      {
        "count": 1,
        "label": "Wild card",
        "odds": {
          "common": 55,
          "uncommon": 30,
          "rare": 12,
          "epic": 3
        }
      },
      {
        "count": 1,
        "label": "Rare or better (guaranteed)",
        "odds": {
          "rare": 81.8,
          "epic": 14,
          "legendary": 4,
          "chase": 0.2
        }
      }
    ],
    "holo": {
      "common": 2,
      "uncommon": 3,
      "rare": 6,
      "epic": 10,
      "legendary": 15,
      "chase": 25
    }
  },
  "cards": [
    {
      "id": "001",
      "name": "Card 001",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "002",
      "name": "Card 002",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 002. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "003",
      "name": "Card 003",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "004",
      "name": "Card 004",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "005",
      "name": "Card 005",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "006",
      "name": "Card 006",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 006. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "007",
      "name": "Card 007",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "008",
      "name": "Card 008",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 008. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "009",
      "name": "Card 009",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "010",
      "name": "Card 010",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "011",
      "name": "Card 011",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "012",
      "name": "Card 012",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 012. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "013",
      "name": "Card 013",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "014",
      "name": "Card 014",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 014. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "015",
      "name": "Card 015",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "016",
      "name": "Card 016",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "017",
      "name": "Card 017",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "018",
      "name": "Card 018",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 018. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "019",
      "name": "Card 019",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "020",
      "name": "Card 020",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 020. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "021",
      "name": "Card 021",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "022",
      "name": "Card 022",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "023",
      "name": "Card 023",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "024",
      "name": "Card 024",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 024. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "025",
      "name": "Card 025",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "026",
      "name": "Card 026",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 026. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "027",
      "name": "Card 027",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "028",
      "name": "Card 028",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "029",
      "name": "Card 029",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "030",
      "name": "Card 030",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 030. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "031",
      "name": "Card 031",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "032",
      "name": "Card 032",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 032. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "033",
      "name": "Card 033",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "034",
      "name": "Card 034",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "035",
      "name": "Card 035",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "036",
      "name": "Card 036",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 036. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "037",
      "name": "Card 037",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "038",
      "name": "Card 038",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 038. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "039",
      "name": "Card 039",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "040",
      "name": "Card 040",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "041",
      "name": "Card 041",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "042",
      "name": "Card 042",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 042. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "043",
      "name": "Card 043",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "044",
      "name": "Card 044",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 044. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "045",
      "name": "Card 045",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "046",
      "name": "Card 046",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "047",
      "name": "Card 047",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "048",
      "name": "Card 048",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 048. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "049",
      "name": "Card 049",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "050",
      "name": "Card 050",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 050. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "051",
      "name": "Card 051",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "052",
      "name": "Card 052",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "053",
      "name": "Card 053",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "054",
      "name": "Card 054",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 054. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "055",
      "name": "Card 055",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "056",
      "name": "Card 056",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 056. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "057",
      "name": "Card 057",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "058",
      "name": "Card 058",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "059",
      "name": "Card 059",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "060",
      "name": "Card 060",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 060. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "061",
      "name": "Card 061",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "062",
      "name": "Card 062",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 062. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "063",
      "name": "Card 063",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "064",
      "name": "Card 064",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "065",
      "name": "Card 065",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "066",
      "name": "Card 066",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 066. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "067",
      "name": "Card 067",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "068",
      "name": "Card 068",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 068. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "069",
      "name": "Card 069",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "070",
      "name": "Card 070",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "071",
      "name": "Card 071",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "072",
      "name": "Card 072",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 072. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "073",
      "name": "Card 073",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "074",
      "name": "Card 074",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 074. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "075",
      "name": "Card 075",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "076",
      "name": "Card 076",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "077",
      "name": "Card 077",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "078",
      "name": "Card 078",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 078. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "079",
      "name": "Card 079",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "080",
      "name": "Card 080",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 080. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "081",
      "name": "Card 081",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "082",
      "name": "Card 082",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "083",
      "name": "Card 083",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "084",
      "name": "Card 084",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 084. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "085",
      "name": "Card 085",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "086",
      "name": "Card 086",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 086. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "087",
      "name": "Card 087",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "088",
      "name": "Card 088",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "089",
      "name": "Card 089",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "090",
      "name": "Card 090",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 090. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "091",
      "name": "Card 091",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "092",
      "name": "Card 092",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 092. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "093",
      "name": "Card 093",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "094",
      "name": "Card 094",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "095",
      "name": "Card 095",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "096",
      "name": "Card 096",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 096. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "097",
      "name": "Card 097",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "098",
      "name": "Card 098",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 098. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "099",
      "name": "Card 099",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "100",
      "name": "Card 100",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "101",
      "name": "Card 101",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "102",
      "name": "Card 102",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 102. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "103",
      "name": "Card 103",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "104",
      "name": "Card 104",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 104. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "105",
      "name": "Card 105",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "106",
      "name": "Card 106",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "107",
      "name": "Card 107",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "108",
      "name": "Card 108",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 108. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "109",
      "name": "Card 109",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "110",
      "name": "Card 110",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 110. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "111",
      "name": "Card 111",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "112",
      "name": "Card 112",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "113",
      "name": "Card 113",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "114",
      "name": "Card 114",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 114. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "115",
      "name": "Card 115",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "116",
      "name": "Card 116",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 116. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "117",
      "name": "Card 117",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "118",
      "name": "Card 118",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "119",
      "name": "Card 119",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "120",
      "name": "Card 120",
      "rarity": "common",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 120. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "121",
      "name": "Card 121",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "122",
      "name": "Card 122",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 122. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "123",
      "name": "Card 123",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "124",
      "name": "Card 124",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "125",
      "name": "Card 125",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "126",
      "name": "Card 126",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 126. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "127",
      "name": "Card 127",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "128",
      "name": "Card 128",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 128. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "129",
      "name": "Card 129",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "130",
      "name": "Card 130",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "131",
      "name": "Card 131",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "132",
      "name": "Card 132",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 132. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "133",
      "name": "Card 133",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "134",
      "name": "Card 134",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 134. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "135",
      "name": "Card 135",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "136",
      "name": "Card 136",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "137",
      "name": "Card 137",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "138",
      "name": "Card 138",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 138. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "139",
      "name": "Card 139",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "140",
      "name": "Card 140",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 140. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "141",
      "name": "Card 141",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "142",
      "name": "Card 142",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "143",
      "name": "Card 143",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "144",
      "name": "Card 144",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 144. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "145",
      "name": "Card 145",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "146",
      "name": "Card 146",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 146. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "147",
      "name": "Card 147",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "148",
      "name": "Card 148",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "149",
      "name": "Card 149",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "150",
      "name": "Card 150",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 150. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "151",
      "name": "Card 151",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "152",
      "name": "Card 152",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 152. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "153",
      "name": "Card 153",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "154",
      "name": "Card 154",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "155",
      "name": "Card 155",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "156",
      "name": "Card 156",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 156. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "157",
      "name": "Card 157",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "158",
      "name": "Card 158",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 158. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "159",
      "name": "Card 159",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "160",
      "name": "Card 160",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "161",
      "name": "Card 161",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "162",
      "name": "Card 162",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 162. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "163",
      "name": "Card 163",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "164",
      "name": "Card 164",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 164. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "165",
      "name": "Card 165",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "166",
      "name": "Card 166",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "167",
      "name": "Card 167",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "168",
      "name": "Card 168",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 168. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "169",
      "name": "Card 169",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "170",
      "name": "Card 170",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 170. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "171",
      "name": "Card 171",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "172",
      "name": "Card 172",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "173",
      "name": "Card 173",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "174",
      "name": "Card 174",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 174. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "175",
      "name": "Card 175",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "176",
      "name": "Card 176",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 176. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "177",
      "name": "Card 177",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "178",
      "name": "Card 178",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "179",
      "name": "Card 179",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "180",
      "name": "Card 180",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 180. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "181",
      "name": "Card 181",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "182",
      "name": "Card 182",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 182. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "183",
      "name": "Card 183",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "184",
      "name": "Card 184",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "185",
      "name": "Card 185",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "186",
      "name": "Card 186",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 186. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "187",
      "name": "Card 187",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "188",
      "name": "Card 188",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 188. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "189",
      "name": "Card 189",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "190",
      "name": "Card 190",
      "rarity": "uncommon",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "191",
      "name": "Card 191",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "192",
      "name": "Card 192",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 192. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "193",
      "name": "Card 193",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "194",
      "name": "Card 194",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 194. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "195",
      "name": "Card 195",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "196",
      "name": "Card 196",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "197",
      "name": "Card 197",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "198",
      "name": "Card 198",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 198. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "199",
      "name": "Card 199",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "200",
      "name": "Card 200",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 200. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "201",
      "name": "Card 201",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "202",
      "name": "Card 202",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "203",
      "name": "Card 203",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "204",
      "name": "Card 204",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 204. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "205",
      "name": "Card 205",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "206",
      "name": "Card 206",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 206. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "207",
      "name": "Card 207",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "208",
      "name": "Card 208",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "209",
      "name": "Card 209",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "210",
      "name": "Card 210",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 210. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "211",
      "name": "Card 211",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "212",
      "name": "Card 212",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 212. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "213",
      "name": "Card 213",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "214",
      "name": "Card 214",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "215",
      "name": "Card 215",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "216",
      "name": "Card 216",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 216. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "217",
      "name": "Card 217",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "218",
      "name": "Card 218",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 218. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "219",
      "name": "Card 219",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "220",
      "name": "Card 220",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "221",
      "name": "Card 221",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "222",
      "name": "Card 222",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 222. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "223",
      "name": "Card 223",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "224",
      "name": "Card 224",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 224. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "225",
      "name": "Card 225",
      "rarity": "rare",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "226",
      "name": "Card 226",
      "rarity": "epic",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "227",
      "name": "Card 227",
      "rarity": "epic",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "228",
      "name": "Card 228",
      "rarity": "epic",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 228. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "229",
      "name": "Card 229",
      "rarity": "epic",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "230",
      "name": "Card 230",
      "rarity": "epic",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 230. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "231",
      "name": "Card 231",
      "rarity": "epic",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "232",
      "name": "Card 232",
      "rarity": "epic",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "233",
      "name": "Card 233",
      "rarity": "epic",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "234",
      "name": "Card 234",
      "rarity": "epic",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 234. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "235",
      "name": "Card 235",
      "rarity": "epic",
      "subtitle": "Placeholder",
      "details": "Details box: anything goes. A stat line, a quick bio, a fun fact, or a one-liner."
    },
    {
      "id": "236",
      "name": "Card 236",
      "rarity": "epic",
      "subtitle": "Placeholder",
      "details": "Sample text for Card 236. When the real set arrives, this box can hold a stat line, a fun fact, a short story, or nothing at all."
    },
    {
      "id": "237",
      "name": "Card 237",
      "rarity": "epic",
      "subtitle": "Placeholder",
      "details": "Details TBD."
    },
    {
      "id": "238",
      "name": "Card 238",
      "rarity": "epic",
      "subtitle": "Placeholder",
      "details": "Example stat line: 12.3 · 45 · 6.78 | Example fun fact: this card is a placeholder."
    },
    {
      "id": "239",
      "name": "Card 239",
      "rarity": "epic",
      "subtitle": "Placeholder",
      "details": "\"Flavor text goes here, in quotes, like a little story.\" (placeholder)"
    },
    {
      "id": "240",
      "name": "Card 240",
      "rarity": "epic",
      "subtitle": "Placeholder",
      "details": "Placeholder details for Card 240. Stats, fun facts, or flavor text go here."
    },
    {
      "id": "241",
      "name": "Card 241",
      "rarity": "legendary",
      "subtitle": "Placeholder",
      "details": "Legendary placeholder. Real details coming soon: stats, a fun fact, or flavor text."
    },
    {
      "id": "242",
      "name": "Card 242",
      "rarity": "legendary",
      "subtitle": "Placeholder",
      "details": "Legendary placeholder. Real details coming soon: stats, a fun fact, or flavor text."
    },
    {
      "id": "243",
      "name": "Card 243",
      "rarity": "legendary",
      "subtitle": "Placeholder",
      "details": "Legendary placeholder. Real details coming soon: stats, a fun fact, or flavor text."
    },
    {
      "id": "244",
      "name": "Card 244",
      "rarity": "legendary",
      "subtitle": "Placeholder",
      "details": "Legendary placeholder. Real details coming soon: stats, a fun fact, or flavor text."
    },
    {
      "id": "245",
      "name": "Card 245",
      "rarity": "legendary",
      "subtitle": "Placeholder",
      "details": "Legendary placeholder. Real details coming soon: stats, a fun fact, or flavor text."
    },
    {
      "id": "246",
      "name": "Card 246",
      "rarity": "legendary",
      "subtitle": "Placeholder",
      "details": "Legendary placeholder. Real details coming soon: stats, a fun fact, or flavor text."
    },
    {
      "id": "247",
      "name": "Card 247",
      "rarity": "chase",
      "subtitle": "Placeholder",
      "details": "Chase card. One of the rarest pulls in the set (about 1 in 2,000 packs for this exact card). Real details coming soon."
    },
    {
      "id": "248",
      "name": "Card 248",
      "rarity": "chase",
      "subtitle": "Placeholder",
      "details": "Chase card. One of the rarest pulls in the set (about 1 in 2,000 packs for this exact card). Real details coming soon."
    },
    {
      "id": "249",
      "name": "Card 249",
      "rarity": "chase",
      "subtitle": "Placeholder",
      "details": "Chase card. One of the rarest pulls in the set (about 1 in 2,000 packs for this exact card). Real details coming soon."
    },
    {
      "id": "250",
      "name": "Card 250",
      "rarity": "chase",
      "subtitle": "Placeholder",
      "details": "Chase card. One of the rarest pulls in the set (about 1 in 2,000 packs for this exact card). Real details coming soon."
    }
  ]
});
